Create Poscon Banner
thepensionsregulator/react-components pull request #235
Opened 2020-12-03 09:48 UTC by HarryAmmon

#### Fixes AB#73965

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

#### Reviewers should focus on:

#### Screenshot

2020-12-03 11:49 UTC, sussexrick commented
Just one tip up-front - the banner should have a `role="alert"` attribute, eg `<div role="alert"></div>`. This means that assistive technology will draw attention to it when it appears (eg a screen reader would read it out).

2020-12-03 17:51 UTC, HarryAmmon commented
Marking as ready for review, why is centre-ing divs such a pain?

2020-12-04 12:01 UTC, sussexrick requested changes

2020-12-04 12:01 UTC, sussexrick commented on packages/layout/src/components/poscon/poscon.tsx
> +			<Flex cfg={{ justifyContent: 'space-between', bg: color }}>
<Flex /> generates a <div />, so you can probably just put `role=alert` onto that to save unnecessary nesting. Also the redundant `<div></div>` can go. If you're using it to create space then that should be done with CSS, eg add a class to the Flex or update `Styles.content`.

2020-12-04 12:02 UTC, sussexrick commented
Re: your comment about centring divs, if you're stuck on some CSS feel free to show me on a call and we can debug together.

2020-12-08 14:08 UTC, HarryAmmon commented on packages/layout/src/components/buttons/buttons.tsx
> +			<button type={'button'} onClick={onClick}></button>
cross has been moved inside button to act as label

2020-12-08 14:11 UTC, HarryAmmon commented on packages/icons/src/icons.tsx
> +		<SVG testId="cross" {...svgProps} width="15px">
`role='img` and `aria-label` added as SVG is used as label for `<CrossButton/>`

2020-12-08 14:11 UTC, HarryAmmon commented on packages/layout/src/components/buttons/buttons.module.scss
> +	display: grid;
Placing the `<Cross />` component inside the `<button>` means this is no longer required

2020-12-08 14:13 UTC, HarryAmmon commented
> Re: your comment about centring divs, if you're stuck on some CSS feel free to show me on a call and we can debug together.

A refactor has made centre-ing this easier, used Flexbox to position child items

2020-12-08 14:20 UTC, Sitecorgi approved these changes

2020-12-08 14:20 UTC, merged