Bug/79431 february dates fix
thepensionsregulator/react-components pull request #295
Opened 2021-01-18 15:57 UTC by tapiwamukwewa

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

#### Reviewers should focus on:

Added a validation check for february dates above the 29th (30 & 31)

#### Screenshot

2021-01-18 16:41 UTC, dotcom9 requested changes

2021-01-18 16:41 UTC, dotcom9 commented on packages/forms/src/elements/date/date.tsx
> +// JS new Date(2020,02,31) evaluates to a valid date in March, this check is to validate that we still
This function is a good candidate for a unit test. Perhaps worth adding one?

2021-01-18 18:04 UTC, vrojastpr commented
Agree with the need of unit tests for the `datePassesFebruaryCheck` function.

2021-01-19 08:35 UTC, dotcom9 commented on packages/forms/src/__tests__/SameMonthDateValidator.spec.ts
> +		expect(validator.ResolvedDateIsInSameMonth('2020', '01', '30')).toBeTruthy();
Did you mean this test to be for the 31st Jan?

2021-01-19 08:36 UTC, dotcom9 reviewed
Like the unit test and the way you created a separate validator class.

2021-01-19 08:41 UTC, dotcom9 approved these changes

2021-01-19 09:45 UTC, vrojastpr approved these changes

2021-01-19 10:18 UTC, merged